from htmlwriter import *
from elements import *


class Home:
    def __init__(self):
        self.filename = "index.html"
        self.page = HtmlWriter(self.filename)

    def generate(self):
        self.page.writeline("<!doctype html>")
        self.page.pushtag("html")

        head = PageHead()
        head.insert(Stylesheet("main.css"))
        head.insert(Stylesheet("buttons.css"))
        head.insert(Stylesheet("home.css"))
        head.insert(Favicon())
        head.generate(self.page)

        navbar = NavBar()
        navbar.generate(self.page)

        body = PageElement("body")
        coverdiv1 = Div("coverdiv1")
        name = Paragraph("Sebastian Fabian", "class=\"coverhugetext\"")
        subtitle = Paragraph("Software Engineer", "class=\"coversubtitle\"")
        textcoverdiv1 = Div("covertext")
        textcoverdiv1.insert(name)
        textcoverdiv1.insert(subtitle)
        coverdiv1.insert(Div("distance"))
        coverdiv1.insert(textcoverdiv1)
        body.insert(coverdiv1)

        coverdiv2 = Div("purplecoverdiv")
        about = Paragraph(
            "I am a software professional with an M.Sc in Engineering and an eye for details. During my studies I worked part-time in sales, which has given me an excellent hand with people, something I can put to great use in my current work driving product performance and scalability. My studies concluded in 2016 with my master thesis concerning route prediction at a major automotive manufacturer, which resulted in a patented algorithm.",
            "class=\"coverbread\"")
        about2 = Paragraph("This site was created as a hobby project. Although no expert in design by any means, I greatly enjoy building things. It is generated by Python code available from my GitHub.", "class=\"coverbread\"")
        textcoverdiv2 = Div("covertext")
        textcoverdiv2.insert(about)
        textcoverdiv2.insert(about2)
        coverdiv2.insert(Div("distance"))
        coverdiv2.insert(textcoverdiv2)
        coverdiv2.insert(Div("distance"))
        body.insert(coverdiv2)

        coverdiv3 = Div("coverdiv3")
        construction = Paragraph("These are some of the things I enjoy.", "class=\"coverbread\"")
        textcoverdiv3 = Div("covertext")
        textcoverdiv3.insert(construction)
        textcoverdiv3.insert(Div("half_small_distance"))
        table = Table(2, 3, "stretchtable")
        passions = [
            ("flag", "I speak four (natural) languages!"),
            ("camera", "Photography"),
            ("education", "Learning new things"),
            ("dashboard", "Classic and modern cars"),
            ("wrench", "Tinkering with things"),
            ("plane", "Travel")
        ]
        passions.reverse()
        for x in range(table.rows):
            for y in range(table.cols):
                passion = passions.pop()
                div = Div()
                div.insert(Glyphicon(passion[0]))
                div.insert(Paragraph(passion[1]))
                div.insert(Div("half_small_distance"))
                table.insertat(x, y, div)
        textcoverdiv3.insert(table)
        coverdiv3.insert(Div("distance"))
        coverdiv3.insert(textcoverdiv3)
        coverdiv3.insert(Div("distance"))
        body.insert(coverdiv3)

        experiencecover = Div("bluecoverdiv")
        experiences = Experiences()
        experiencecover.insert(experiences)
        body.insert(experiencecover)

        coverdiv4 = Div("coverdiv4")
        textcoverdiv4 = Div("covertext")
        textcoverdiv4.insert(Paragraph("I speak these programming languages.", "class=\"coverbread\""))
        textcoverdiv4.insert(Div("small_distance"))
        table = Table(4, 2, "stretchtable")
        langauges = [
            ".NET/C#",
            "Java",
            "Golang",
            "Groovy",
            "Python",
            "Javascript",
            "C",
            "C++"
        ]
        langauges.reverse()
        for x in range(table.rows):
            for y in range(table.cols):
                lang = langauges.pop()
                div = Div("langdiv")
                div.insert(PageElement("span", "class=\"whitebkg\"", lang))
                div.insert(Div("small_distance"))
                table.insertat(x, y, div)
        textcoverdiv4.insert(table)
        coverdiv4.insert(Div("distance"))
        coverdiv4.insert(textcoverdiv4)
        coverdiv4.insert(Div("distance"))
        body.insert(coverdiv4)

        body.insert(Links())
        body.insert(Contact())

        body.generate(self.page)

        self.page.close()
